CREATE TABLE telco_customer_churn (
    customer_id VARCHAR(50),
    gender VARCHAR(20),
    age INTEGER,
    senior_citizen VARCHAR(10),
    partner VARCHAR(10),
    dependents VARCHAR(10),
    tenure_months INTEGER,
    phone_service VARCHAR(10),
    multiple_lines VARCHAR(20),
    internet_service VARCHAR(30),
    online_security VARCHAR(10),
    online_backup VARCHAR(10),
    device_protection VARCHAR(10),
    tech_support VARCHAR(10),
    streaming_tv VARCHAR(10),
    streaming_movies VARCHAR(10),
    contract VARCHAR(30),
    paperless_billing VARCHAR(10),
    payment_method VARCHAR(50),
    monthly_charge NUMERIC(10,2),
    total_charges NUMERIC(12,2),
    churn_label VARCHAR(10),
    churn_value INTEGER,
    churn_score INTEGER,
    cltv NUMERIC(12,2),
    churn_reason VARCHAR(255)
);

SELECT *
FROM telco_customer_churn
LIMIT 1;

DROP TABLE IF EXISTS telco_customer_churn;

CREATE TABLE telco_customer_churn (
    customer_id VARCHAR(50),
    count INTEGER,
    country VARCHAR(100),
    state VARCHAR(100),
    city VARCHAR(100),
    zip_code INTEGER,
    lat_long VARCHAR(100),
    latitude NUMERIC(10,6),
    longitude NUMERIC(10,6),
    gender VARCHAR(20),
    senior_citizen VARCHAR(10),
    partner VARCHAR(10),
    dependents VARCHAR(10),
    tenure_months INTEGER,
    phone_service VARCHAR(10),
    multiple_lines VARCHAR(30),
    internet_service VARCHAR(30),
    online_security VARCHAR(30),
    online_backup VARCHAR(30),
    device_protection VARCHAR(30),
    tech_support VARCHAR(30),
    streaming_tv VARCHAR(30),
    streaming_movies VARCHAR(30),
    contract VARCHAR(30),
    paperless_billing VARCHAR(10),
    payment_method VARCHAR(50),
    monthly_charges NUMERIC(10,2),
    total_charges NUMERIC(12,2),
    churn_label VARCHAR(10),
    churn_value INTEGER,
    churn_score INTEGER,
    cltv NUMERIC(12,2),
    churn_reason VARCHAR(255)
);

CREATE TABLE telco_customer_churn (
    customer_id VARCHAR(50),
    gender VARCHAR(20),
    age INTEGER,
    under_30 VARCHAR(10),
    senior_citizen VARCHAR(10),
    married VARCHAR(10),
    dependents VARCHAR(10),
    number_of_dependents INTEGER,
    country VARCHAR(100),
    state VARCHAR(100),
    city VARCHAR(100),
    zip_code VARCHAR(20),
    latitude NUMERIC(10,6),
    longitude NUMERIC(10,6),
    population INTEGER,
    quarter VARCHAR(20),
    referred_a_friend VARCHAR(10),
    number_of_referrals INTEGER,
    tenure_in_months INTEGER,
    offer VARCHAR(100),
    phone_service VARCHAR(10),
    avg_monthly_long_distance_charges NUMERIC(10,2),
    multiple_lines VARCHAR(30),
    internet_service VARCHAR(30),
    internet_type VARCHAR(30),
    avg_monthly_gb_download NUMERIC(10,2),
    online_security VARCHAR(30),
    online_backup VARCHAR(30),
    device_protection_plan VARCHAR(30),
    premium_tech_support VARCHAR(30),
    streaming_tv VARCHAR(30),
    streaming_movies VARCHAR(30),
    streaming_music VARCHAR(30),
    unlimited_data VARCHAR(30),
    contract VARCHAR(30),
    paperless_billing VARCHAR(10),
    payment_method VARCHAR(50),
    monthly_charge NUMERIC(10,2),
    total_charges NUMERIC(12,2),
    total_refunds NUMERIC(12,2),
    total_extra_data_charges NUMERIC(12,2),
    total_long_distance_charges NUMERIC(12,2),
    total_revenue NUMERIC(12,2),
    satisfaction_score INTEGER,
    customer_status VARCHAR(30),
    churn_label VARCHAR(10),
    churn_score INTEGER,
    cltv NUMERIC(12,2),
    churn_category VARCHAR(100),
    churn_reason VARCHAR(255)
);

SELECT * FROM telco_customer_churn
LIMIT 10